import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service | cronwiz.dev",
  description: "Terms of service for cronwiz.dev — usage terms for our cron expression tools and monitoring service.",
  alternates: { canonical: "https://cronwiz.dev/terms" },
}

export default function TermsPage() {
  return (
    <>
      <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: May 13, 2026</p>

      <div className="space-y-6 text-muted-foreground leading-relaxed">
        <h2 className="text-xl font-semibold text-foreground">1. Acceptance</h2>
        <p>
          By using cronwiz.dev, you agree to these terms. If you do not agree, do not use the service.
        </p>

        <h2 className="text-xl font-semibold text-foreground">2. Service description</h2>
        <p>
          cronwiz.dev provides AI-powered cron expression generation, explanation, validation, and testing tools. These tools are provided free of charge with no guarantee of availability or accuracy.
        </p>

        <h2 className="text-xl font-semibold text-foreground">3. Free tools</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>The cron generator, explainer, validator, and tester are free to use without an account</li>
          <li>We may impose rate limits (currently 10 requests per minute per IP)</li>
          <li>We reserve the right to modify or discontinue free tools at any time</li>
        </ul>

        <h2 className="text-xl font-semibold text-foreground">4. AI-generated output</h2>
        <p>
          Cron expressions and explanations are generated by AI (Claude). While we design our prompts for accuracy, AI output may contain errors. <strong className="text-foreground">Always test cron expressions before deploying to production.</strong> We are not liable for damages caused by incorrect cron expressions.
        </p>

        <h2 className="text-xl font-semibold text-foreground">5. Paid services (upcoming)</h2>
        <p>
          AI Cron Monitoring is a paid service launching Q3 2026. Specific terms for paid services will be provided at launch. Waitlist signup does not constitute a purchase or commitment.
        </p>

        <h2 className="text-xl font-semibold text-foreground">6. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Abuse rate limits or attempt to circumvent them</li>
          <li>Use automated scripts to scrape or overload the service</li>
          <li>Use the service for any unlawful purpose</li>
          <li>Reverse engineer or redistribute the AI system prompts</li>
        </ul>

        <h2 className="text-xl font-semibold text-foreground">7. Intellectual property</h2>
        <p>
          The cronwiz.dev website, branding, and AI prompts are our intellectual property. Cron expressions generated by the tool are yours to use freely — we claim no ownership over the output.
        </p>

        <h2 className="text-xl font-semibold text-foreground">8. Disclaimer of warranties</h2>
        <p>
          The service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that the service will be uninterrupted, error-free, or that AI-generated cron expressions will be correct for your specific use case.
        </p>

        <h2 className="text-xl font-semibold text-foreground">9. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, cronwiz.dev and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
        </p>

        <h2 className="text-xl font-semibold text-foreground">10. Changes</h2>
        <p>
          We may update these terms at any time. Continued use of the service constitutes acceptance of the updated terms.
        </p>

        <h2 className="text-xl font-semibold text-foreground">11. Contact</h2>
        <p>
          Questions about these terms? Email{" "}
          <a href="mailto:hi@cronwiz.dev" className="text-primary hover:underline">hi@cronwiz.dev</a>.
        </p>
      </div>
    </>
  )
}
