import { ArrowDown, Github } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CronTool } from "@/components/cron-tool"
import { Features } from "@/components/features"
import { UseCases } from "@/components/use-cases"
import { Comparison } from "@/components/comparison"
import { Waitlist } from "@/components/waitlist"
import { FAQ } from "@/components/faq"
import { Footer } from "@/components/footer"

export default function HomePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-border bg-background/80 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="font-semibold text-foreground flex items-center gap-2">
            <span className="w-6 h-6 rounded bg-primary flex items-center justify-center text-primary-foreground text-xs font-bold">
              C
            </span>
            cronwiz.dev
          </Link>
          <nav className="hidden md:flex items-center gap-6 text-sm text-muted-foreground">
            <Link href="#tool" className="hover:text-foreground transition-colors">Tool</Link>
            <Link href="#features" className="hover:text-foreground transition-colors">Features</Link>
            <Link href="#faq" className="hover:text-foreground transition-colors">FAQ</Link>
          </nav>
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <Github className="w-4 h-4" />
            <span className="hidden sm:inline">GitHub</span>
          </a>
        </div>
      </header>

      {/* Hero */}
      <section className="pt-32 pb-12 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-foreground mb-6 text-balance">
            Cron expressions in any flavor,{" "}
            <span className="text-primary">generated by AI</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-8 leading-relaxed text-balance">
            Type schedules in plain English. Get production-ready cron for Linux, AWS, Kubernetes, GitHub Actions, Vercel, and 5 more platforms — with built-in DST handling, plan limits, and edge-case warnings.
          </p>
          <Button size="lg" asChild>
            <a href="#tool" className="gap-2">
              <ArrowDown className="w-4 h-4" />
              Try it now — no signup, no credit card
            </a>
          </Button>
        </div>
      </section>

      {/* Tool Section */}
      <section id="tool" className="py-12 px-4 scroll-mt-20">
        <CronTool />
      </section>

      {/* Features */}
      <section id="features" className="scroll-mt-20">
        <Features />
      </section>

      {/* Use Cases */}
      <UseCases />

      {/* Comparison */}
      <Comparison />

      {/* Waitlist */}
      <Waitlist />

      {/* FAQ */}
      <section id="faq" className="scroll-mt-20">
        <FAQ />
      </section>

      {/* Footer */}
      <Footer />
    </div>
  )
}
